# Generated by Django 4.2.3 on 2023-07-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='usuario.png', upload_to=''),
        ),
    ]
